// <auto-generated />
namespace GB.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Order_IsFinishedAt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order_IsFinishedAt));
        
        string IMigrationMetadata.Id
        {
            get { return "201905231801233_Order_IsFinishedAt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
